### ISSUE TITLE
Tiles are not loading

### ISSUE THREAD

**Issue by paj1s** [JLyne/LiveAtlas#550]
Whatever i do the tiles won't load, i had this problem earlier and somehow fixed it on one server by fiddling with symlinks and stuff but still i don't know what is the cause of this. Now i want to merge my maps again into one ui and i have this problem again. Every php file is accessible also im using the dynmap_world.json instead of mysql. In dynmap i have my tilespath set to another disk and webpath to my website path in var/www i have a folder for each server in there and i keep the update wepath in dynmap on because sometimes when it's off the files in standalone folder won't update either. But dynmap is working as normal and in live atlas i can only see the players when they join, no tiles.

**Comment by paj1s** [comment]
PS: in console there's only this one error
index.a82d2095.js:20 Uncaught (in promise) Error: Request returned invalid json
    at me.fetchJSON (index.a82d2095.js:20:7057)
    at async Proxy.getMarkerSets (index.a82d2095.js:20:33545)
    at async Proxy.populateWorld (index.a82d2095.js:20:34563)
